// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjourRAyGrSwEPOLRHFg-VBIlAzH7g6Qk',
    appId: '1:352594857715:web:7e597176d589ac6814f186',
    messagingSenderId: '352594857715',
    projectId: 'codelabmodul',
    authDomain: 'codelabmodul.firebaseapp.com',
    storageBucket: 'codelabmodul.appspot.com',
    measurementId: 'G-1FSGGKDQQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxqQUfCKRSXmb-RdYzz0sTNI3xHLUrlro',
    appId: '1:352594857715:android:7645c6520491c40f14f186',
    messagingSenderId: '352594857715',
    projectId: 'codelabmodul',
    storageBucket: 'codelabmodul.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhN3XIT5ZuCXARtG1Y--4w3Nw-YUN9xqQ',
    appId: '1:352594857715:ios:367959447fa77a4a14f186',
    messagingSenderId: '352594857715',
    projectId: 'codelabmodul',
    storageBucket: 'codelabmodul.appspot.com',
    iosBundleId: 'flutterproject.codelamodul3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhN3XIT5ZuCXARtG1Y--4w3Nw-YUN9xqQ',
    appId: '1:352594857715:ios:367959447fa77a4a14f186',
    messagingSenderId: '352594857715',
    projectId: 'codelabmodul',
    storageBucket: 'codelabmodul.appspot.com',
    iosBundleId: 'flutterproject.codelamodul3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjourRAyGrSwEPOLRHFg-VBIlAzH7g6Qk',
    appId: '1:352594857715:web:f9affe5a1ca2a0c314f186',
    messagingSenderId: '352594857715',
    projectId: 'codelabmodul',
    authDomain: 'codelabmodul.firebaseapp.com',
    storageBucket: 'codelabmodul.appspot.com',
    measurementId: 'G-K8HF6B20SC',
  );
}
